import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Switch, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useFocusEffect } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useAppTheme } from '@/context/ThemeContext';
import { useLanguage } from '@/context/LanguageContext';
import { notificationService, AppNotification, isDemoNotificationMode } from '@/services/notificationService';
import { completedChoresService, CompletedChore } from '@/services/completedChoresService';
import { settingsService, NotificationSettings, settingsDemoMode, UserPreferences } from '@/services/settingsService';

const purple = '#7C5CFC';
const defaultNotifications: NotificationSettings = { chore_reminders:true, chore_completions:true, family_updates:true, announcements:false, reminder_time:'10min' };
export function Component04Screen({ kind }: { kind: 'notifications'|'completed'|'settings'|'notificationSettings'|'preferences'|'about' }) {
  const { theme, setTheme } = useAppTheme(); const { t, language, setLanguage } = useLanguage(); const dark = theme === 'dark';
  const bg = dark ? '#14121F' : '#F8F7FC', card = dark ? '#1F1B2E' : '#fff', fg = dark ? '#fff' : '#1E1B2E', muted = dark ? '#B8B2CC' : '#757288';
  const [items,setItems] = useState<AppNotification[]>([]); const [chores,setChores] = useState<CompletedChore[]>([]); const [filter,setFilter] = useState<'all'|'unread'|'read'>('all'); const [range,setRange] = useState<'all'|'today'|'week'|'month'>('all'); const [query,setQuery] = useState('');
  const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [demo,setDemo] = useState(false); const [notice,setNotice] = useState(''); const [notif,setNotif] = useState(defaultNotifications); const [prefs,setPrefs] = useState<UserPreferences>({theme,language});
  const load = useCallback(async () => { setBusy(true); setError(''); try { if(kind==='notifications'){setItems(await notificationService.getNotifications(filter));setDemo(isDemoNotificationMode());} else if(kind==='completed'){setChores(await completedChoresService.get(range,query));} else if(kind==='notificationSettings'){setNotif(await settingsService.getNotificationSettings());setDemo(settingsDemoMode);} else if(kind==='preferences'){setPrefs(await settingsService.getPreferences());setDemo(settingsDemoMode);} } catch(e) { setError(e instanceof Error ? e.message : 'Unable to load data.'); } finally { setBusy(false); } },[kind,filter,range,query]);
  useFocusEffect(useCallback(()=>{ void load(); },[load]));
  const panel=(children:React.ReactNode)=> <View style={[s.panel,{backgroundColor:card}]}>{children}</View>;
  const banner=demo && <Text style={s.demo}>DEMO / OFFLINE — changes shown here are not saved to the backend.</Text>;
  const title = kind==='notifications'?t('notifications'):kind==='completed'?t('completed_chores_title'):kind==='settings'?t('settings_title'):kind==='notificationSettings'?t('notification_settings'):kind==='preferences'?t('preferences_title'):t('about_title');
  const top=<View style={s.head}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={()=>router.back()} style={s.icon}><Ionicons name="arrow-back" size={22} color={purple}/></Pressable><Text style={[s.title,{color:fg}]}>{title}</Text>{kind!=='notifications'&&<Pressable accessibilityRole="button" accessibilityLabel="Open notifications" onPress={()=>router.push('/home/notifications')} style={s.icon}><Ionicons name="notifications-outline" size={22} color={purple}/></Pressable>}</View>;
  const switchRow=(label:keyof NotificationSettings)=> <View style={s.row} key={label}><Text style={[s.rowTitle,{color:fg}]}>{t(label as any)}</Text><Switch value={notif[label] as boolean} onValueChange={v=>setNotif({...notif,[label]:v})} trackColor={{true:purple}} accessibilityLabel={t(label as any)}/></View>;
  let content:React.ReactNode;
  if(kind==='notifications') content=<>{banner}<Text style={[s.subtitle,{color:muted}]}>{t('notifications_subtitle')}</Text><Pressable style={s.primary} onPress={async()=>{try{await notificationService.markAllRead();setItems(items.map(n=>({...n,is_read:true})));setDemo(isDemoNotificationMode());}catch(e){setError(e instanceof Error?e.message:'Could not update notifications.')}}}><Text style={s.primaryText}>{t('mark_all_read')}</Text></Pressable><View style={s.chips}>{(['all','unread','read'] as const).map(v=><Pressable key={v} onPress={()=>setFilter(v)} style={[s.chip,filter===v&&s.selected]}><Text style={{color:filter===v?'#fff':fg}}>{v==='all'?t('filter_all'):v==='unread'?`${t('filter_unread')} (${items.filter(i=>!i.is_read).length})`:t('filter_read')}</Text></Pressable>)}</View>{busy?<ActivityIndicator color={purple}/>:items.length===0?<Text style={{color:muted}}>{t('no_notifications')}</Text>:items.map(n=><Pressable key={n.id} onPress={async()=>{if(!n.is_read){try{await notificationService.markRead(n.id);setItems(items.map(x=>x.id===n.id?{...x,is_read:true}:x));setDemo(isDemoNotificationMode());}catch(e){setError(e instanceof Error?e.message:'Could not update notification.')}}}}>{panel(<View style={s.row}><Ionicons name={n.type==='chore_completed'?'checkmark-circle':'notifications'} size={24} color={n.type==='chore_completed'?'#22C55E':purple}/><View style={{flex:1}}><Text style={[s.rowTitle,{color:fg}]}>{n.title}</Text><Text style={{color:muted}}>{n.message}</Text></View>{!n.is_read&&<View style={s.dot}/>}</View>)}</Pressable>)}</>;
  else if(kind==='completed') content=<><Text style={[s.subtitle,{color:muted}]}>{t('completed_chores_subtitle')}</Text><TextInput value={query} onChangeText={setQuery} placeholder={t('search_placeholder')} placeholderTextColor={muted} style={[s.input,{backgroundColor:card,color:fg}]} accessibilityLabel={t('search_placeholder')}/><View style={s.chips}>{(['all','today','week','month'] as const).map(v=><Pressable key={v} onPress={()=>setRange(v)} style={[s.chip,range===v&&s.selected]}><Text style={{color:range===v?'#fff':fg}}>{v==='all'?t('filter_all'):v==='today'?t('filter_today'):v==='week'?t('filter_week'):t('filter_month')}</Text></Pressable>)}</View>{busy?<ActivityIndicator color={purple}/>:error?<Text style={{color:'#EF4444'}}>{error}</Text>:chores.length===0?<Text style={{color:muted}}>No completed chores match this search.</Text>:chores.map(c=>panel(<View key={c.id} style={s.row}><Ionicons name="checkmark-circle" size={24} color="#22C55E"/><View style={{flex:1}}><Text style={[s.rowTitle,{color:fg}]}>{c.title}</Text><Text style={{color:muted}}>By {c.assignee_name||c.creator_name||'Member'}</Text></View><Text style={{color:muted}}>{new Date(c.completed_at||c.updated_at).toLocaleDateString()}</Text></View>))}</>;
  else if(kind==='settings') content=<>{banner}{[['notification_settings','notification_settings_sub','notifications','/home/notification-settings'],['reminder_time','reminder_time_sub','time','/home/notification-settings'],['theme','theme_sub','color-palette','/home/preferences'],['language','language_sub','language','/home/preferences'],['about_app','about_app_sub','information-circle','/home/about']].map(([a,b,icon,path])=><Pressable key={a} onPress={()=>router.push(path as any)}>{panel(<View style={s.row}><Ionicons name={icon as any} size={24} color={purple}/><View style={{flex:1}}><Text style={[s.rowTitle,{color:fg}]}>{t(a as any)}</Text><Text style={{color:muted}}>{t(b as any)}</Text></View><Ionicons name="chevron-forward" size={20} color={muted}/></View>)}</Pressable>)}</>;
  else if(kind==='notificationSettings') content=<>{banner}{(['chore_reminders','chore_completions','family_updates','announcements'] as const).map(switchRow)}<Text style={[s.rowTitle,{color:fg,marginTop:12}]}>{t('reminder_time')}</Text>{(['10min','30min','1hour','1day'] as const).map((v,i)=><Pressable key={v} disabled={!notif.chore_reminders} onPress={()=>setNotif({...notif,reminder_time:v})} style={s.row}><Text style={{color:notif.chore_reminders?fg:muted}}>{t((['10_min','30_min','1_hour','1_day'] as const)[i])}</Text><Ionicons name={notif.reminder_time===v?'radio-button-on':'radio-button-off'} size={22} color={purple}/></Pressable>)}<Pressable style={s.primary} onPress={async()=>{try{await settingsService.saveNotificationSettings(notif);setDemo(false);setNotice(t('settings_saved'));}catch(e){setDemo(true);setError(e instanceof Error?e.message:'Unable to save settings.');}}}><Text style={s.primaryText}>{t('save_settings')}</Text></Pressable></>;
  else if(kind==='preferences') content=<>{banner}<Text style={[s.rowTitle,{color:fg}]}>{t('theme')}</Text>{(['light','dark'] as const).map(v=><Pressable key={v} style={[s.choice,{backgroundColor:card,borderColor:theme===v?purple:'#ddd'}]} onPress={async()=>{await setTheme(v);setPrefs({...prefs,theme:v});try{await settingsService.savePreferences({...prefs,theme:v,language});setDemo(false);}catch(e){setDemo(true);setError(e instanceof Error?e.message:'Could not sync preference.');}}}><Text style={{color:fg}}>{v==='light'?t('light_theme'):t('dark_theme')}</Text></Pressable>)}<Text style={[s.rowTitle,{color:fg,marginTop:16}]}>{t('language')}</Text>{(['en','si','ta'] as const).map(v=><Pressable key={v} style={[s.choice,{backgroundColor:card,borderColor:language===v?purple:'#ddd'}]} onPress={async()=>{await setLanguage(v);setPrefs({...prefs,language:v});try{await settingsService.savePreferences({...prefs,theme,language:v});setDemo(false);}catch(e){setDemo(true);setError(e instanceof Error?e.message:'Could not sync preference.');}}}><Text style={{color:fg}}>{v==='en'?t('english'):v==='si'?t('sinhala'):t('tamil')}</Text></Pressable>)}</>;
  else content=panel(<View style={{alignItems:'center',gap:12,padding:20}}><Ionicons name="home" size={52} color={purple}/><Text style={[s.title,{color:fg}]}>ChoreSync</Text><Text style={{color:muted}}>{t('tagline')}</Text><Text style={{color:muted}}>Version 1.0.0 · Build 100</Text><Text style={{color:purple}}>{t('privacy_policy')} · {t('terms_of_service')}</Text></View>);
  return <SafeAreaView style={[s.safe,{backgroundColor:bg}]}>{top}<ScrollView contentContainerStyle={s.body} refreshControl={<RefreshControl refreshing={busy} onRefresh={()=>void load()} tintColor={purple}/ >}>{content}{!!notice&&<Text style={{color:'#22C55E'}}>{notice}</Text>}{!!error&&kind!=='completed'&&<Text style={{color:'#EF4444'}}>{error}</Text>}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1},head:{flexDirection:'row',alignItems:'center',paddingHorizontal:16,paddingVertical:8,gap:8},icon:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:20,fontWeight:'800',flex:1},body:{padding:16,paddingBottom:36,gap:12},subtitle:{fontSize:14,marginBottom:4},panel:{borderRadius:16,padding:16,marginVertical:3},row:{flexDirection:'row',alignItems:'center',gap:12},rowTitle:{fontSize:15,fontWeight:'700'},primary:{backgroundColor:purple,minHeight:48,borderRadius:14,alignItems:'center',justifyContent:'center',paddingHorizontal:16},primaryText:{color:'#fff',fontWeight:'700'},chips:{flexDirection:'row',gap:8,flexWrap:'wrap'},chip:{borderRadius:18,paddingVertical:9,paddingHorizontal:14,backgroundColor:'#EFEAFF'},selected:{backgroundColor:purple},dot:{width:9,height:9,borderRadius:5,backgroundColor:purple},input:{minHeight:48,borderRadius:14,paddingHorizontal:14},choice:{borderWidth:1.5,borderRadius:14,padding:16},demo:{backgroundColor:'#FFF3CD',color:'#705400',padding:10,borderRadius:10,fontWeight:'700'}});
