export const crudTranslations = {
  en: {
    my_reminders: 'My Reminders', manage_announcements: 'Manage Announcements', household_announcements: 'Household Announcements',
    crud_add: 'Add', crud_view: 'View', crud_edit: 'Edit', crud_delete: 'Delete', crud_cancel: 'Cancel', crud_save: 'Save', crud_title: 'Title', crud_note: 'Note (optional)', crud_message: 'Message', crud_chore: 'Choose your assigned chore', crud_time: 'Local date/time (YYYY-MM-DD HH:mm)', crud_search: 'Search', crud_all: 'All', crud_upcoming: 'Upcoming', crud_past: 'Past', crud_pending: 'Pending', crud_unavailable: 'Chore unavailable', crud_draft: 'Draft', crud_published: 'Published', crud_empty: 'No matching records.', crud_no_chores: 'No eligible pending chores assigned to you.', crud_saved: 'Saved successfully.', crud_deleted: 'Deleted successfully.', crud_confirm: 'Delete this record?', crud_required: 'Complete the required fields within the displayed limits.', crud_future: 'Enter a valid future local date/time.', crud_delivery: 'Reminders are saved. Automatic notification delivery is not available.', crud_no_family: 'Join a household to view announcements.', crud_created: 'Created', crud_updated: 'Updated', crud_retry: 'Refresh', crud_saving: 'Saving…', crud_load_error: 'Unable to load. Please try again.', crud_save_error: 'Unable to save. Please try again.',
  },
  si: {
    my_reminders: 'මගේ මතක් කිරීම්', manage_announcements: 'නිවේදන කළමනාකරණය', household_announcements: 'පවුලේ නිවේදන',
    crud_add: 'එක් කරන්න', crud_view: 'බලන්න', crud_edit: 'සංස්කරණය', crud_delete: 'මකන්න', crud_cancel: 'අවලංගු කරන්න', crud_save: 'සුරකින්න', crud_title: 'මාතෘකාව', crud_note: 'සටහන (විකල්ප)', crud_message: 'පණිවිඩය', crud_chore: 'ඔබට පැවරූ කාර්යයක් තෝරන්න', crud_time: 'දේශීය දිනය/වේලාව (YYYY-MM-DD HH:mm)', crud_search: 'සොයන්න', crud_all: 'සියල්ල', crud_upcoming: 'ඉදිරියේදී', crud_past: 'පසුගිය', crud_pending: 'පොරොත්තු', crud_unavailable: 'කාර්යය ලබා ගත නොහැක', crud_draft: 'කෙටුම්පත', crud_published: 'ප්‍රකාශිත', crud_empty: 'ගැළපෙන වාර්තා නැත.', crud_no_chores: 'ඔබට පැවරූ සුදුසු කාර්යයන් නැත.', crud_saved: 'සාර්ථකව සුරකින ලදී.', crud_deleted: 'සාර්ථකව මකන ලදී.', crud_confirm: 'මෙම වාර්තාව මකන්නද?', crud_required: 'පෙන්වා ඇති සීමාවන් තුළ අවශ්‍ය තොරතුරු පුරවන්න.', crud_future: 'වලංගු අනාගත දේශීය දිනයක්/වේලාවක් ඇතුළත් කරන්න.', crud_delivery: 'මතක් කිරීම් සුරකිනු ලැබේ. ස්වයංක්‍රීය දැනුම්දීම් යැවීම ලබා ගත නොහැක.', crud_no_family: 'නිවේදන බැලීමට පවුලකට එක්වන්න.', crud_created: 'සාදන ලද්දේ', crud_updated: 'යාවත්කාලීන කරන ලද්දේ', crud_retry: 'නැවත ලබා ගන්න', crud_saving: 'සුරකිමින්…', crud_load_error: 'ලබා ගැනීමට නොහැක. නැවත උත්සාහ කරන්න.', crud_save_error: 'සුරැකීමට නොහැක. නැවත උත්සාහ කරන්න.',
  },
  ta: {
    my_reminders: 'எனது நினைவூட்டல்கள்', manage_announcements: 'அறிவிப்புகளை நிர்வகி', household_announcements: 'குடும்ப அறிவிப்புகள்',
    crud_add: 'சேர்', crud_view: 'பார்', crud_edit: 'திருத்து', crud_delete: 'நீக்கு', crud_cancel: 'ரத்து', crud_save: 'சேமி', crud_title: 'தலைப்பு', crud_note: 'குறிப்பு (விருப்பம்)', crud_message: 'செய்தி', crud_chore: 'உங்களுக்கு ஒதுக்கப்பட்ட வேலையைத் தேர்ந்தெடுக்கவும்', crud_time: 'உள்ளூர் தேதி/நேரம் (YYYY-MM-DD HH:mm)', crud_search: 'தேடு', crud_all: 'அனைத்தும்', crud_upcoming: 'வரவிருக்கும்', crud_past: 'கடந்தவை', crud_pending: 'நிலுவை', crud_unavailable: 'வேலை கிடைக்கவில்லை', crud_draft: 'வரைவு', crud_published: 'வெளியிடப்பட்டது', crud_empty: 'பொருந்தும் பதிவுகள் இல்லை.', crud_no_chores: 'உங்களுக்கு ஒதுக்கப்பட்ட தகுதியான வேலைகள் இல்லை.', crud_saved: 'வெற்றிகரமாகச் சேமிக்கப்பட்டது.', crud_deleted: 'வெற்றிகரமாக நீக்கப்பட்டது.', crud_confirm: 'இந்தப் பதிவை நீக்கவா?', crud_required: 'காட்டப்பட்ட வரம்புகளுக்குள் தேவையான தகவல்களை நிரப்பவும்.', crud_future: 'செல்லுபடியாகும் எதிர்கால உள்ளூர் தேதி/நேரத்தை உள்ளிடவும்.', crud_delivery: 'நினைவூட்டல்கள் சேமிக்கப்படுகின்றன. தானியங்கி அறிவிப்பு வழங்கல் கிடைக்கவில்லை.', crud_no_family: 'அறிவிப்புகளைப் பார்க்க குடும்பத்தில் சேரவும்.', crud_created: 'உருவாக்கப்பட்டது', crud_updated: 'புதுப்பிக்கப்பட்டது', crud_retry: 'புதுப்பி', crud_saving: 'சேமிக்கிறது…', crud_load_error: 'ஏற்ற முடியவில்லை. மீண்டும் முயற்சிக்கவும்.', crud_save_error: 'சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
  },
};
